[package]
name = "bomber-ai"
version = "0.1.1"
authors = ["Kyohei Ishihata <ishihata.k.tech@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
